### ISSUE TITLE
Hey, I wished to connnect with you and didnt know any other way.

### ISSUE THREAD

**Issue by sbmxc** [maxking/linux-security-papers#1]
here is my portfolio website sbmsc.github.io we can connect on any platform of your choice just let me know. I want your guidance regarding gsoc and mailman. Thank you.

**Comment by maxking** [comment]
How did you find out about me? 

I am going to close this issue since it is not related to the project.

**Comment by sbmxc** [comment]
Contributors in mailman.

**Comment by maxking** [comment]
Please consider using official channels to reach out about GSoC. The ideas page for Mailman mentioned on the Google's website should have enough pointers to get started.
